language: node_js
sudo: required
services:
    - docker

before_install:
    - docker build -t atzepeng/dockercourse -f ./react-image/Dockerfile.dev ./react-image

script:
    - docker run -e CI=true atzepeng/dockercourse npm run test
    