language: node_js
sudo: required
services:
    - docker
before_install:
    - docker build -t atzepeng/dockercourse -f ./$context/Dockerfile.dev ./$context
script:
    - docker run -e CI=true atzepeng/dockercourse npm run test
before_deploy: 
    - cd $context
deploy:
    provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-2"
    app: "docker-react"
    env: "dockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-316398516609"
    bucket_path: "docker-react"
    on:
        branch: master
        condition: $doDeploy = true
