version: '3'

services: 
    redis-server:
        image: 'redis'
    
    node-app:
        restart: on-failure
        build: ./node-image
        ports:
            - "8080:8080"

#    environment:
#        - CHOKIDAR_USEPOLLING=true